### ISSUE TITLE
ValidateSalt rejects valid salts

### ISSUE THREAD

**Issue by mietek** [ncb000gt/node.bcrypt.js#365]
Example:
```
> var salt = bcrypt.genSaltSync(31);
undefined

> salt;
'$2a$31$vLQjJ9zAWyUwiXLeQDa6w.'

> bcrypt.hashSync("hello", salt);
Error: Invalid salt. Salt must be in the form of: $Vers$log2(NumRounds)$saltvalue
```

**Comment by ranisalt** [comment]
I think it's because in the middle of the salt a null byte was generated (0x00). While this is perfecly allowed since a salt is a byte array and not a null-terminated string (NTS), when it's converted to a JS string it is converted as a NTS.

I had the same issue with [node-argon2](https://github.com/ranisalt/node-argon2) and I decided to use buffers instead. Also it uses the crypto module instead of implementing an own salt generation utility since Argon2 does not require signature to the salt.

**Comment by mietek** [comment]
I think it’s because nobody expected salts of size 31 to be used.

**Comment by ranisalt** [comment]
What's the problem with salts of arbitrary length?

**Comment by defunctzombie** [comment]
31 is not the length, it is the number of "rounds" or complexity of the salt. I don't know what our upper bound is but 31 is way more than you need. The default we use is 10 and I believe that is considered sufficient today.
