### ISSUE TITLE
Consider XOR instead of equals for the comparator

### ISSUE THREAD

**Issue by melograph85** [ncb000gt/node.bcrypt.js#369]
The guide _[Salted Password Hashing - Doing it Right](https://crackstation.net/hashing-security.htm)_ claims that XOR is better than `==` for a slow-equals comparison function to mitigate timing attacks:

> The reason we need to use XOR instead of the "==" operator to compare integers is that "==" is usually translated/compiled/interpreted as a branch.... The branching makes the code execute in a different amount of time depending on the equality of the integers and the CPU's internal branch prediction state.

This module's implementation [currently uses the `!=` operator](https://github.com/ncb000gt/node.bcrypt.js/blob/master/src/bcrypt_node.cc#L241). Indeed, clang compiles this to code that branches, which can result in variable-time execution:

```
        ## ../src/bcrypt_node.cc:240
next:
        cmp     ebx, esi
        jl      continue
        cmp     eax, esi
        jl      continue
        movzx   edi, byte ptr [r15 + rsi]
        movzx   ecx, byte ptr [rbp + rsi - 176]
        cmp     ecx, edi
        je      continue
        xor     r8d, r8d
continue:
        inc     rsi
        cmp     esi, edx
        jl      next
```

(The above is edited output from running node-gyp's build command on bcrypt_node.cc with the additional `-S -masm=intel` options.)

The page mentioned has more information. I figured this might be worth bringing up.

**Comment by mlogan** [comment]
That page has a lot of bad advice, such as using SHA256 for hashing passwords. (See: https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2007/july/enough-with-the-rainbow-tables-what-you-need-to-know-about-secure-password-schemes/)

The particular suggestion of using timing attacks against password hashes is just bogus. Timing attacks work against HMACs because you can send anything you want as the signature. Once you guess the first byte, you hold that constant and work on the second byte. But you can't hold the first byte of the output of a cryptographic hash constant while probing for the second byte. If you could, you could just reverse the hash, and break most or all of modern crypto. (See: http://security.stackexchange.com/questions/9192/timing-attacks-on-password-hashes)
