### ISSUE TITLE
Question about implementation of async methods

### ISSUE THREAD

**Issue by dtoubelis** [ncb000gt/node.bcrypt.js#443]
I have question about implementation of async methods. Here is a scenario - let's say we setup number of rounds to 15 (2^15) for hash calculation and and it would take few seconds to generate/validate a hash. I wonder what behaviour to expect from the server within these few seconds - will bcrypt implementation (a) hog the event loop for few seconds while running rounds, (b) calculate rounds in a separate thread triggering an event on the main loop when done, (c) calculate rounds in the same thread releasing event loop after each iteration?

I'm asking this question in a context of DoS mitigation in order to better understand risks. It would also be nice to have this mentioned it in README. Thanks in advance.

**Comment by defunctzombie** [comment]
a) no
b) yes
c) no

**Comment by dtoubelis** [comment]
Excellent. Thnaks.

**Comment by lcrespom** [comment]
I see in the README.md the async version is recommended, but it does not explain why. I suggest you explain it there, otherwise it leaves us users scratching our heads on what would be the problem with using the sync version.

**Comment by defunctzombie** [comment]
It has to do with how the nodejs event loop works. Because the hashing done by bcrypt is cpu intensive, if you don't use async, this hashing operation will block the event loop and prevent your application from servicing any other inbound requests or events.

If you want to google for more details on this and make a PR to update the readme with language you think would be appropriate, I would welcome such a contribution.

**Comment by lcrespom** [comment]
Thank you for your offering... I have never done a PR before so I will learn about it and get back to you.

**Comment by lcrespom** [comment]
I just created the PR, please take a look at it

**Comment by RichardWright** [comment]
Hey - would anyone mind if I reopened this? I feel like the explanation is missing a key part, namely that *another* thread(does the native extension use the same address space) is involved. If a computation is CPU bound then making it async won't stop it blocking the event loop. I'm so glad I found this issue because I've pondered this frequently and this is the first time I've got some closure.
